services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Bus_Tracking_Management_System
      DB_USER: postgres
      DB_PASSWORD: rahul
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      UPLOAD_PATH: /app/uploads/CommentImages
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: mlm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: camelq123
    ports:
      - "8082:80"
    depends_on:
      - db    

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahul
      POSTGRES_DB: Bus_Tracking_Management_System
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data    

volumes:
  db_data:
