version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: bus_tracking_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: bus_tracking_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - bus_tracking_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: bus_tracking_redis_dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - bus_tracking_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for Database Management
  adminer:
    image: adminer:4.8.1
    container_name: bus_tracking_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - bus_tracking_dev_network
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  bus_tracking_dev_network:
    driver: bridge
